# Generated by Django 5.2.7 on 2025-10-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringEntry',
            fields=[
                ('id', models.CharField(primary_key=True, max_length=64, editable=False)),
                ('value', models.TextField(unique=True)),
                ('length', models.PositiveIntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.PositiveIntegerField()),
                ('word_count', models.PositiveIntegerField()),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
