# Generated by Django 5.2.7 on 2025-10-22 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stringentry',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
